spring:
  application:
    name: Management
  main:
    allow-bean-definition-overriding: true
    jvm-arguments: -Dio.netty.resolve.dns.native.disabled=true

  data:
    mongodb:
      uri: mongodb://localhost:27017/mydatabase

  graphql:
    graphiql:
      enabled: true

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379
    password: # Leave blank if no password is set
    timeout: 5000ms

  kafka:
    bootstrap:
      servers: http://localhost:9092
    acknowledge:
      manual:
        commit: true
    replying:
      template:
        enabled: false
    consumer:
      group-id: my-consumer-group # Specify the consumer group ID
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    org.springframework.data.redis: DEBUG